# Generated by Django 4.0.3 on 2024-11-15 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(max_length=255)),
                ('dosage_form', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField()),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complains', models.TextField(max_length=600)),
                ('vitals', models.TextField(max_length=600)),
                ('diagnosis', models.TextField(max_length=600)),
                ('referrals', models.TextField(default='')),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('time_issued', models.TimeField(auto_now_add=True)),
                ('next_checkup', models.DateField(blank=True, null=True)),
                ('is_referred', models.BooleanField(default=False)),
                ('doctor_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='appointments.doctorappointment')),
            ],
        ),
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('dosage_frequency', models.CharField(choices=[('Morning', 'Morning'), ('Noon', 'Noon'), ('Night', 'Night'), ('Morning + Noon', 'Morning + Noon'), ('Noon + Night', 'Noon + Night'), ('Morning + Night', 'Morning + Night'), ('Morning + Noon+ Night', 'Morning + Noon + Night')], default='', max_length=200)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='medicines.prescription')),
            ],
        ),
    ]
