# Generated by Django 4.0.3 on 2024-09-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_referred',
            field=models.BooleanField(default=False),
        ),
    ]
