# Generated by Django 5.1.2 on 2024-10-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualifications',
            field=models.CharField(default='MBBS', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(default='medicine', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default_user.png', upload_to='profile_pictures/'),
        ),
    ]
