# Generated by Django 4.0.3 on 2024-11-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraisingcertificate',
            name='attachments',
        ),
        migrations.AddField(
            model_name='fundraisingrequest',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
