# Generated by Django 5.1.2 on 2024-11-08 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrescribedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_tests', to='medicines.prescription')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_tests.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('result', models.TextField()),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='test_reports/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('prescribed_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_reports', to='medical_tests.prescribedtest')),
            ],
        ),
    ]
