# Generated by Django 4.0.3 on 2024-09-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_tests', '0001_initial'),
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribedtest',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_tests', to='medicines.prescription'),
        ),
        migrations.AddField(
            model_name='prescribedtest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_tests.test'),
        ),
    ]
