# Generated by Django 4.0.3 on 2024-09-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_tests', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='availability',
            new_name='is_available',
        ),
    ]
